services:
    - type: web
      name: brasil-burger-gestionnaire
      runtime: docker
      region: frankfurt
      plan: free
      branch: symfony
      rootDir: BrasilBurgerGestionnaire
      dockerfilePath: ./Dockerfile
      envVars:
          - key: APP_ENV
            value: prod
          - key: APP_SECRET
            generateValue: true
          - key: DATABASE_URL
            value: postgresql://neondb_owner:npg_pz18CVGHDXoh@ep-summer-night-aboebfme-pooler.eu-west-2.aws.neon.tech:5432/neondb?sslmode=require&charset=utf8
          - key: CLOUDINARY_CLOUD_NAME
            value: djeiy36k9
          - key: CLOUDINARY_API_KEY
            value: 613148843794364
          - key: CLOUDINARY_API_SECRET
            value: 8e50wkglx9nDCuj7IaaC-mC8_-0
